### ISSUE TITLE
vagrant ssh command not work

### ISSUE THREAD

**Issue by Fashaun** [ppggff/vagrant-qemu#22]
Hi, 

Did you test with vagrant ssh command ?

<img width="626" alt="image" src="https://user-images.githubusercontent.com/5792071/193735628-b2d25992-e4d9-435c-96fa-a5bb06bb450a.png">

**Comment by ppggff** [comment]
yes, `vagrant ssh` works

**Comment by brandonros** [comment]
I got it to work with

```
Vagrant.configure("2") do |config|
  config.vm.box = "generic/alpine316"
  config.vm.provider "qemu" do |qe|
    qe.arch = "x86_64"
    qe.machine = "q35"
    qe.cpu = "max"
    qe.net_device = "virtio-net-pci"
  end
end

```

but not 

```
Vagrant.configure('2') do |config|
  config.vm.define "vm" do |config|
    config.vm.synced_folder '.', '/vagrant', disabled: true
    config.vm.box = "debian/bullseye64"
    config.vm.provider "qemu" do |qe|
      qe.arch = "x86_64"
      qe.machine = "q35"
      qe.cpu = "max"
      qe.net_device = "virtio-net-pci"
    end
  end
end
```

does it depend on the box? any way to make it work for Debian and not Alpine only?

**Comment by brandonros** [comment]
https://github.com/ppggff/vagrant-qemu/issues/5#issuecomment-1118158687 probably related to this

> Notes, you also need add config.vm.synced_folder ".", "/vagrant", type: "smb", smb_host: "10.0.2.2"
to the Vagrantfile due to a know issue.
