### ISSUE TITLE
make communicate two guests on the same network

### ISSUE THREAD

**Issue by bertuz** [ppggff/vagrant-qemu#30]
Hi, I'm unsuccessfully trying to make two/multiple guests defined within my vagrantfile to communicate among each other. 
Is it possible? As far as I see netwroking is still in progress and a `user` type is sent by default. I'm wondering if I could use another solution to create a unique virtual network  the guests share

**Comment by ppggff** [comment]
Currently, this plugin uses "user mode networking" for simplicity. I think there still be able to connect multiple guests together:
* Use forward port: vm A forwards 80 to host:8080, vm B connects to host:8080 (for example, 10.0.2.2:8080)
* Use "Socket" networking to connect guests' network, see https://wiki.qemu.org/Documentation/Networking#Advanced_user_networking_options and https://lists.gnu.org/archive/html/qemu-discuss/2014-11/msg00020.html for details
* Use manual created bridge, and bridge config for qemu, see https://futurewei-cloud.github.io/ARM-Datacenter/qemu/network-aarch64-qemu-guests/ as a example (just found by google)

The latter two methods require the use of `extra_qemu_args` to set up the new network config.

I haven't tested them (except the first one, I connected to ssh port of another vm),
feel free to report any problems.

**Comment by bertuz** [comment]
I think we cannot use the socket option because a default `user` type is added by default.

for instance:

```
      config.vm.define "kubemaster" do |node|
        # Name shown in the GUI
        node.vm.provider "qemu" do |vb|
            vb.name = "kubemaster"
            vb.memory = 2048
            vb.cpus = 2
            vb.ssh_port = 5022
            vb.extra_netdev_args = "id=mynet0,net=192.168.51.0/24,dhcpstart=192.168.51.10,socket=on"
            
        end
```

produces this error:

```
Stderr: qemu-system-aarch64: -netdev user,id=net0,hostfwd=tcp::5022-:22,id=mynet0,net=192.168.51.0/24,dhcpstart=192.168.51.10,socket=on: Invalid parameter 'socket'
```

**Comment by bertuz** [comment]
done it! Thanks for your support. the `extra_qemu_args` does help. I'm using Mac OS' Hypervisor with its own networking system.

```
            vb.extra_qemu_args = "-M accel=hvf -netdev user,id=mynet0,net=192.168.76.0/24,dhcpstart=192.168.76.9 -netdev vmnet-shared,id=mynet1 -device virtio-net-pci,netdev=mynet1,mac=54:54:00:55:55:5#{i}".split

```
