### ISSUE TITLE
windows node doesnt boot fully : how to debug it ? 

### ISSUE THREAD

**Issue by jayunit100** [ppggff/vagrant-qemu#34]
we now have a two node recipe , one linux and one windows, thanks for so much help thus far.

however, we are finding that `vagrant ssh` doesnt work on the windows node.

I assume ill need to get the boot/bios logs from QEMU to see why ?

**Comment by ppggff** [comment]
Please provide the Vagrantfile, I will try it.

To debug this, I recommend trying to boot the vm with the raw qemu command (may be with display enabled) first, because this plugin is a wrapper to qemu command.

**Comment by jayunit100** [comment]
things are now booting.  this issue was resolved by some of pramitas previous issues that were filed.  thanks !
