### ISSUE TITLE
USB Forwarding?

### ISSUE THREAD

**Issue by andronat** [ppggff/vagrant-qemu#43]
Is it possible to attach usb from MacOS? I'm running Apple Silicon M1 on Ventura 13.3?

**Comment by ppggff** [comment]
What kind of usb device is it?

**Comment by andronat** [comment]
It's a serial adapter like this [one](https://www.amazon.co.uk/gp/product/B07BBPX8B8/ref=ppx_yo_dt_b_asin_title_o01_s01?ie=UTF8&psc=1). I'm using it for some IoT device developing.

**Comment by andronat** [comment]
I case someone is interested this is how I attached a usb device:
```
qe.extra_qemu_args = %W[-usb -device qemu-xhci -device usb-host,vendorid=0x<vendorid here>,productid=0x<productid here>,]
```
